FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN python manage.py collectstatic --noinput || true
RUN python manage.py migrate || true

CMD ["gunicorn", "reklama.wsgi:application", "--bind", "0.0.0.0:8020"]

