# Generated by Django 5.2.3 on 2025-06-20 10:02

import django.db.models.deletion
import reklamaproject.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(help_text='Uzbekcha nomi', max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(help_text='Ruscha nomi', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Joy raqami, masalan: 1, 2, 3')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi_uz', models.CharField(default='Reklama nomi', help_text='Uzbekcha reklama nomi', max_length=255)),
                ('Reklama_nomi_ru', models.CharField(default='Reklama nomi', help_text='Ruscha reklama nomi', max_length=255)),
                ('Qurilma_turi_uz', models.CharField(default='led', help_text='Uzbekcha qurilma turi', max_length=100)),
                ('Qurilma_turi_ru', models.CharField(default='led', help_text='Ruscha qurilma turi', max_length=100)),
                ('Ijarachi_uz', models.CharField(blank=True, help_text="Ijarachi_o'zbekcha", max_length=255, null=True)),
                ('Ijarachi_ru', models.CharField(blank=True, help_text='Ijarachi_ruscha', max_length=255, null=True)),
                ('Shartnoma_raqami_uz', models.CharField(blank=True, help_text="Shartnoma raqami o'zbekcha", max_length=100, null=True)),
                ('Shartnoma_raqami_ru', models.CharField(blank=True, help_text='Shartnoma raqami ruscha', max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi_uz', models.CharField(choices=[('dona', 'Dona'), ('kv_metr', 'Kv metr'), ('komplekt', 'Komplekt')], default='dona', help_text="O'lchov birligi o'zbekcha", max_length=50)),
                ('O_lchov_birligi_ru', models.CharField(choices=[('дона', 'Дона'), ('кв. метр', 'Кв. метр'), ('комплект', 'Комплект')], default='дона', help_text="O'lchov birligi ruscha", max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, default=None, null=True, upload_to='contracts/', validators=[reklamaproject.validators.validate_file_extension])),
                ('photo', models.ImageField(upload_to='ad_photos/', validators=[reklamaproject.validators.validate_file_extension])),
                ('contact_number', models.CharField(default='+998', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='reklamaproject.position')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi_uz', models.CharField(max_length=255)),
                ('Reklama_nomi_ru', models.CharField(max_length=255)),
                ('Qurilma_turi_uz', models.CharField(max_length=100)),
                ('Qurilma_turi_ru', models.CharField(max_length=100)),
                ('Ijarachi_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('Ijarachi_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('Shartnoma_raqami_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('Shartnoma_raqami_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi_uz', models.CharField(max_length=50)),
                ('O_lchov_birligi_ru', models.CharField(max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, null=True, upload_to='contracts_archive/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ad_photos_archive/')),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='reklamaproject.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.position')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(help_text='Uzbekcha nomi', max_length=100, null=True, unique=True)),
                ('name_ru', models.CharField(help_text='Ruscha nomi', max_length=100, null=True, unique=True)),
                ('schema_image', models.ImageField(blank=True, help_text='Bekat sxemasi rasmi', null=True, upload_to='station_schemas/')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='reklamaproject.metroline')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='reklamaproject.station'),
        ),
    ]
