# Generated by Django 5.2.3 on 2025-06-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Pozitsiya', 'verbose_name_plural': 'Pozitsiyalar'},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('station', 'number')},
        ),
    ]
