# Generated by Django 5.2.3 on 2025-06-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='schema_image',
            field=models.ImageField(blank=True, help_text='Bekat sxemasi rasmi', null=True, upload_to='station_schemas/'),
        ),
    ]
