# Generated by Django 5.2.3 on 2025-09-25 10:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ijarachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ijarachi_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='advertisementarchive',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='station',
            name='x',
        ),
        migrations.RemoveField(
            model_name='station',
            name='y',
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='advertisementarchive',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='position',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='reklamaproject.metroline'),
        ),
        migrations.AlterField(
            model_name='station',
            name='schema_image',
            field=models.FileField(blank=True, help_text='Bekat sxemasi (rasm yoki PDF)', null=True, upload_to='station_schemas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='Ijarachi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.ijarachi'),
        ),
        migrations.AlterField(
            model_name='advertisementarchive',
            name='Ijarachi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.ijarachi'),
        ),
    ]
