# Generated by Django 5.2.3 on 2025-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='x',
            field=models.FloatField(blank=True, help_text='Horizontal position (0-100%)', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='y',
            field=models.FloatField(blank=True, help_text='Vertical position (0-100%)', null=True),
        ),
    ]
