# Generated by Django 5.2.3 on 2025-11-18 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShartnomaSummasiArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shartnomasummasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='reklamaproject.advertisementarchive')),
            ],
        ),
    ]
