# Generated by Django 5.2.3 on 2025-06-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0002_alter_advertisement_o_lchov_birligi_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='O_lchov_birligi_ru',
            field=models.CharField(choices=[('штука', 'Щтука'), ('кв. метр', 'Кв. метр'), ('комплект', 'Комплект')], default='штука', help_text="O'lchov birligi ruscha", max_length=50),
        ),
    ]
