# Generated by Django 5.2.3 on 2025-06-20 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0002_station_schema_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi_uz', models.CharField(max_length=255)),
                ('Reklama_nomi_ru', models.CharField(max_length=255)),
                ('Qurilma_turi_uz', models.CharField(max_length=100)),
                ('Qurilma_turi_ru', models.CharField(max_length=100)),
                ('Ijarachi_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('Ijarachi_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('Shartnoma_raqami_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('Shartnoma_raqami_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi_uz', models.CharField(max_length=50)),
                ('O_lchov_birligi_ru', models.CharField(max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, null=True, upload_to='contracts_archive/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ad_photos_archive/')),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='reklamaproject.advertisement')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.position')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
