# Generated by Django 5.2.3 on 2025-11-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0002_shartnomasummasiarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='shartnomasummasi',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
