# Generated by Django 5.2.3 on 2025-07-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0002_station_x_station_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='x',
        ),
        migrations.RemoveField(
            model_name='station',
            name='y',
        ),
    ]
