# Generated by Django 5.2.3 on 2025-11-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0003_shartnomasummasi_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shartnomasummasiarchive',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
