# Generated by Django 5.2.3 on 2025-11-19 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0004_shartnomasummasiarchive_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='advertisementarchive',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.depo'),
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Format: 0001-0002-0003-0004', max_length=19, unique=True)),
                ('schema_image', models.FileField(blank=True, null=True, upload_to='train_schemas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='reklamaproject.depo')),
            ],
        ),
        migrations.CreateModel(
            name='TrainPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='reklamaproject.train')),
            ],
            options={
                'unique_together': {('train', 'number')},
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='train_position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='reklamaproject.trainposition'),
        ),
        migrations.AddField(
            model_name='advertisementarchive',
            name='train_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.trainposition'),
        ),
    ]
