# Generated by Django 5.2.3 on 2025-11-19 11:56

import django.db.models.deletion
import reklamaproject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0005_depo_advertisementarchive_depo_train_trainposition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementarchive',
            name='train_position',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='train_position',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('station', 'number')},
        ),
        migrations.AddField(
            model_name='position',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.train'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='Shartnoma_fayl',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[reklamaproject.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='Shartnoma_raqami',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.station'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('station', 'number'), ('train', 'number')},
        ),
        migrations.DeleteModel(
            name='TrainPosition',
        ),
    ]
