# Generated by Django 5.2.3 on 2025-11-19 12:05

import django.db.models.deletion
import reklamaproject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0006_remove_advertisementarchive_train_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementarchive',
            name='depo',
        ),
        migrations.RemoveField(
            model_name='train',
            name='depo',
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('station', 'number')},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='Shartnoma_fayl',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contracts/', validators=[reklamaproject.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='Shartnoma_raqami',
            field=models.CharField(blank=True, help_text="Shartnoma raqami o'zbekcha", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='reklamaproject.station'),
        ),
        migrations.DeleteModel(
            name='Depo',
        ),
        migrations.RemoveField(
            model_name='position',
            name='train',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
