# Generated by Django 5.2.3 on 2025-11-19 12:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import reklamaproject.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0007_remove_advertisementarchive_depo_remove_train_depo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='TCH-1, TCH-2 va hokazo', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarakaTarkibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarkib', models.CharField(help_text='0001-0002-0003-0004', max_length=100, unique=True)),
                ('schema_image', models.FileField(blank=True, help_text='Bekat sxemasi (rasm yoki PDF)', null=True, upload_to='haraka_tarkibi_schemas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('depo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haraka_tarkiblari', to='reklamaproject.depo')),
            ],
        ),
        migrations.CreateModel(
            name='TarkibAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi', models.CharField(default='Reklama nomi', max_length=255)),
                ('Shartnoma_raqami', models.CharField(blank=True, help_text="Shartnoma raqami o'zbekcha", max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi', models.CharField(choices=[('dona', 'Dona'), ('kv_metr', 'Kv metr'), ('komplekt', 'Komplekt')], default='dona', max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, default=None, null=True, upload_to='contracts/', validators=[reklamaproject.validators.validate_file_extension])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ad_photos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ijarachi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.ijarachi')),
                ('Qurilma_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.turi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarkib_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarkibPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='Pozitsiya raqami, masalan: 1, 2, 3', max_length=100)),
                ('haraka_tarkibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarkib_positions', to='reklamaproject.harakatarkibi')),
            ],
        ),
        migrations.CreateModel(
            name='TarkibAdvertisementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reklama_nomi', models.CharField(max_length=255)),
                ('Shartnoma_raqami', models.CharField(blank=True, max_length=100, null=True)),
                ('Shartnoma_muddati_boshlanishi', models.DateField()),
                ('Shartnoma_tugashi', models.DateField()),
                ('O_lchov_birligi', models.CharField(max_length=50)),
                ('Qurilma_narxi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Egallagan_maydon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Shartnoma_summasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Shartnoma_fayl', models.FileField(blank=True, null=True, upload_to='contracts_archive/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ad_photos_archive/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Ijarachi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.ijarachi')),
                ('Qurilma_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.turi')),
                ('depo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.depo')),
                ('original_ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='reklamaproject.tarkibadvertisement')),
                ('tarkib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.harakatarkibi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.tarkibposition')),
            ],
        ),
        migrations.AddField(
            model_name='tarkibadvertisement',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarkib_advertisement', to='reklamaproject.tarkibposition'),
        ),
    ]
