# Generated by Django 5.2.3 on 2025-11-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0008_depo_harakatarkibi_tarkibadvertisement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HarakaTarkibi',
            new_name='HarakatTarkibi',
        ),
    ]
