# Generated by Django 5.2.3 on 2025-11-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0009_rename_harakatarkibi_harakattarkibi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harakattarkibi',
            name='depo',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='depo',
        ),
        migrations.RemoveField(
            model_name='tarkibposition',
            name='haraka_tarkibi',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='tarkib',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisement',
            name='Ijarachi',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisement',
            name='Qurilma_turi',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisement',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='original_ad',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='Ijarachi',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='Qurilma_turi',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tarkibadvertisementarchive',
            name='user',
        ),
        migrations.DeleteModel(
            name='Depo',
        ),
        migrations.DeleteModel(
            name='HarakatTarkibi',
        ),
        migrations.DeleteModel(
            name='TarkibAdvertisement',
        ),
        migrations.DeleteModel(
            name='TarkibPosition',
        ),
        migrations.DeleteModel(
            name='TarkibAdvertisementArchive',
        ),
    ]
