# Generated by Django 5.2.3 on 2025-11-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0011_depo_harakattarkibi_tarkibadvertisement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarkibposition',
            old_name='haraka_tarkibi',
            new_name='harakat_tarkibi',
        ),
    ]
