# Generated by Django 5.2.3 on 2025-11-21 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0013_tarkibposition_created_at_tarkibposition_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarkibShartnomaSummasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shartnomasummasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reklama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reklamaproject.tarkibadvertisement')),
                ('tarkib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='reklamaproject.tarkibposition')),
            ],
        ),
    ]
