# Generated by Django 5.2.3 on 2025-11-21 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0014_tarkibshartnomasummasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarkibshartnomasummasi',
            name='reklama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarkibtolovlar', to='reklamaproject.tarkibadvertisement'),
        ),
        migrations.AlterField(
            model_name='tarkibshartnomasummasi',
            name='tarkib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reklamaproject.tarkibposition'),
        ),
    ]
