# Generated by Django 5.2.3 on 2025-11-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0015_alter_tarkibshartnomasummasi_reklama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarkibshartnomasummasi',
            name='tarkib',
        ),
    ]
