# Generated by Django 5.2.3 on 2025-11-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0016_remove_tarkibshartnomasummasi_tarkib'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarkibAdvertisementArchiveShartnomaSummasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shartnomasummasi', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reklama_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarkibtolovlar', to='reklamaproject.tarkibadvertisementarchive')),
            ],
        ),
    ]
