# Generated by Django 5.2.3 on 2025-11-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0017_tarkibadvertisementarchiveshartnomasummasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarkibposition',
            name='position',
            field=models.CharField(help_text='Pozitsiya raqami, masalan: 1, 2, 3', max_length=100, unique=True),
        ),
    ]
