# Generated by Django 5.2.3 on 2025-11-24 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklamaproject', '0018_alter_tarkibposition_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarkibposition',
            name='position',
            field=models.CharField(help_text='Pozitsiya raqami, masalan: 1, 2, 3', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tarkibposition',
            constraint=models.UniqueConstraint(fields=('harakat_tarkibi', 'position'), name='unique_position_per_tarkib'),
        ),
    ]
